version: '3'

services:
  myapp:
        build: .
        container_name: "myapp"
        links:
            - mongoserver
        depends_on:
            - mongoserver
  mongoserver:
    image: 'mongo:3.7.9'
    container_name: "mongodb"
    ports:
      - '27017:27017'
    volumes:
      - 'data-volume:/data/db'

volumes:
  data-volume: